### ISSUE TITLE
FIX Master stopped working in VS Code 1.53.1

### ISSUE THREAD

**Issue by soul-ride** [GaryHughes/FixMaster#28] opened 2021-02-11 12:48 UTC
Hi,
This is awesome extension and I've been using it actively. Unfortunately, lately it stopped working in VS Code due to some reason.

It just hangs on "Finding and formatting FIX messages.." notification in bottom right corner. Message stays there until you restart VS Code. 

My VS code info:

Version: 1.53.1 (user setup)
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:29:42.785Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Appreciate if this can be fixed as there are basically no other alternatives for VS Code.

Thanks in advance!

**Comment by GaryHughes** [comment] 2021-02-12 00:30
Thanks I will investigate this.

**Comment by GaryHughes** [comment] 2021-02-12 07:24
I can't reproduce this, I've test on Mac, Windows, and Ubuntu with versions 1.53.1, 1.53.2, and a couple of lower versions with no issues. It might be caused by something in your input data, do you have a file that exhibits the problem that you can share?

**Comment by soul-ride** [comment] 2021-02-12 09:21
Hi Garry,
You are right, looks like there is a problem only with Heartbeat messages.

This message parsed by extension without issues:
8=FIX.4.49=11835=434=243=Y49=SENDER-152=20210211-07:59:20.99756=RECEIVER-1122=20210211-07:59:20.99736=5123=Y10=047

While on this Hearbeat message extension hangs:
8=FIX.4.49=7635=034=649=SENDER-152=20210211-07:59:50.92156=RECEIVER-110=230

Reproducible on 2 different machines.

**Comment by soul-ride** [comment] 2021-02-12 09:25
If I try to parse these messages together:
8=FIX.4.49=11835=434=243=Y49=SENDER-152=20210211-07:59:20.99756=RECEIVER-1122=20210211-07:59:20.99736=5123=Y10=047
8=FIX.4.49=7635=034=649=SENDER-152=20210211-07:59:50.92156=RECEIVER-110=230

..extension also hangs and first message can't be parsed.

**Comment by GaryHughes** [comment] 2021-02-12 10:02
Ok I can reproduce it now, the default configuration for admin messages is to delete them, if the last entry in the file is an admin message like this heartbeat the call to the editor api to delete that line breaks. In the short term you can change the setting for admin messages to ignore them instead of deleting them. It looks like some kind of bounds bug, I'll work out a fix and push a new version in the next day or two.

**Comment by GaryHughes** [comment] 2021-02-12 11:12
Version 1.6.1 with the fix has been published in the marketplace, thanks for the bug report!

**Closed by GaryHughes** 2021-02-12 11:12 UTC

**Comment by soul-ride** [comment] 2021-02-12 11:46
Can confirm it's working now. Thanks a lot for quick fix :)
